### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by hoektoe** [Halo-Lab/sanity-performance-plugin#6]
The XHR for pageSpeed is returning success, but formatMetrics is causing an issue

`TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at formatMetrics (index.esm.js:3745:31)
    at eval (index.esm.js:3714:40)
    at Array.map (<anonymous>)
    at formatDataList (index.esm.js:3714:27)
    at handleRequest (index.esm.js:4753:20)`
    
    
![CleanShot 2024-09-05 at 15 34 28](https://github.com/user-attachments/assets/ac462edd-0816-4aa2-a7aa-ac5139598550)

**Comment by IiIymik** [comment]
@hoektoe Hello!

Thank you for reporting this issue! We have identified the root cause related to the `formatMetrics` function. This was due to the way undefined or null values were handled in the result set.

We have addressed this problem in the new version of the plugin (1.1.1). In this update, we added proper checks for undefined or null objects and revised the data handling process to prevent such errors.

Please update to version 1.1.1, and let us know if the issue persists or if you encounter any further problems.
